"""Shared base classes and state schemas for Hardware Foundry agents."""

from foundry_agent_base.agent import AgentContext, BaseAgent, StateUpdate
from foundry_agent_base.state import (
    BOM,
    AssemblyDoc,
    BOMItem,
    CADArtifacts,
    Constraints,
    ConnectorSlot,
    CostEvent,
    CostLedger,
    CriticReport,
    EnclosurePCBContract,
    FabOrder,
    FirmwareArtifacts,
    Hole,
    Issue,
    Message,
    PCBArtifacts,
    ProductSpec,
    ProductState,
    Requirement,
    SimResults,
    TestPlanDoc,
    UserManualDoc,
)

__all__ = [
    "AgentContext",
    "AssemblyDoc",
    "BaseAgent",
    "BOM",
    "BOMItem",
    "CADArtifacts",
    "ConnectorSlot",
    "Constraints",
    "CostEvent",
    "CostLedger",
    "CriticReport",
    "EnclosurePCBContract",
    "FabOrder",
    "FirmwareArtifacts",
    "Hole",
    "Issue",
    "Message",
    "PCBArtifacts",
    "ProductSpec",
    "ProductState",
    "Requirement",
    "SimResults",
    "StateUpdate",
    "TestPlanDoc",
    "UserManualDoc",
]
